name: Deploy to S3

on:
  push:
    branches:
      - main  # Or your specific branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC
      contents: read    # To access the repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::595670678499:role/homelessnessnyc_github_role
          aws-region: us-east-1

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://homelessnessnyc.org --delete
